### ISSUE TITLE
An Issue About LuaSTGPlus Legacy

### ISSUE THREAD

**Issue by ghost** [9chu/LuaSTGPlus#10]
您好，@9chu 先生，恕我直言，legacy分支使用的是BSD Lisence，但是它[没有说明是哪个BSD许可证](https://www.gnu.org/licenses/bsd.html)，git存储库的legacy分支也没有附带许可协议。虽然所有的BSD许可证都是开源许可证，但是我觉得既然2.0使用的是MIT许可证的话，那是不是应该给所有的分支更换成同样的许可协议不是更好吗？希望能得到您的回复。

**Comment by Demonese** [comment]
BSD-3

**Comment by ghost** [comment]
> BSD-3

@Demonese 我知道只不过legacy分支上的实在过分敷衍，以至于我担心使用legacy存储库里的代码可能会有法律风险。

**Comment by 9chu** [comment]
你好，严格地说，进行license调整需要获得所有贡献者的同意，并且考虑到legacy分支代码不再进行维护，因此不会对license做任何调整。
在授权范围内使用legacy分支的代码不会有法律风险，相关fork版本也已有多款游戏在steam发售。
但需要注意，legacy代码所用的部分第三方库可能存在授权混乱的情况，需要你自行裁剪。

**Comment by ghost** [comment]
@9chu 感谢您的回答。
