### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by ch3coohlink** [9chu/LuaSTGPlus#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'fcyIO/fcyStream.h': No such file or directory	LuaSTGPlus	c:\users\ch3coohlink\desktop\luastgplus\luastgplus\global.h	30

**Comment by 9chu** [comment]
请按照README的说明将fancy2d也clone下来

**Comment by ch3coohlink** [comment]
唉，其实我已经在文件夹里包含了你的fancy2d，也编译出来了，但是工程结构可能摆错了吧...总之有需要的话我自己再弄弄。
另外想请教一个问题，你觉得多线程和批精灵对提升弹幕引擎性能帮助大吗？还是说弊端更多一些？

**Comment by 9chu** [comment]
@ch3coohlink 不是包含，是平级的两个目录 这样就能找到了
多线程要看是什么样的多线程了，一般逻辑都是在一个线程上跑的，多个线程会引发各种问题
BatchSprite是很古老的技术了，如果想在渲染上做的更好可以考虑一些其他的方案，比如类似Instancing的方法，甚至通过VertexShader的ContanstBuffer来传递参数。

**Comment by ch3coohlink** [comment]
@9chu 感谢你的指点，看来我还是需要了解更多GPU编程方面的知识。
